### ISSUE TITLE
Data methods to support optimization

### ISSUE THREAD

**Issue by eito-fis** [coin-test/coin-test#48]
**Is your feature request related to a problem? Please describe.**
Optimizing strategies is currently poorly supported by coin-test.

**Describe the solution you'd like**
A set of new methods should be added to the composer:
* `.split()`, which takes a time and breaks a composer into two parts. Designed to be used for creating train / test splits.
* `.save()` and `.load()`, which should save and load a composer. Useful for saving processed, split data and re-loading it later for optimization. Also useful for reproducing results.

**Comment by teadetime** [comment]
Split into Two Further issues #54 and #55
