### ISSUE TITLE
Initialize Data Module

### ISSUE THREAD

**Issue by eito-fis** [coin-test/coin-test#5]
**Is your feature request related to a problem? Please describe.**
Creating the initial pass of the data loading / data processing module.

**Describe the solution you'd like**
Some initial module which can take in a CSV and spit out an object containing a dataframe and some time interval value. Should leave room for implementing additional cleaning / processing functionality in the future.

**Comment by eito-fis** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data V1 Implementation](https://trello.com/c/6QmLwBYc/15-data-v1-implementation)

**Comment by teadetime** [comment]
```Dataset Metadata``` will be a metadata class for a dataframe so that we can have multiple dataframes as discussed today.
