### ISSUE TITLE
Automatic Data Download

### ISSUE THREAD

**Issue by eito-fis** [coin-test/coin-test#9]
**Is your feature request related to a problem? Please describe.**
As of now, the data module depends on the user of the package importing and transforming data such that it fits our DataFrame schema. This seems like a fairly cumbersome tasks for users, and is a worse workflow than the API-based options other libraries offer.

**Describe the solution you'd like**
We should make the passing of a DataFrame optional and update the `Dataset` to pull from the [Binance API](https://github.com/binance/binance-public-data) when the DataFrame is not specified.

**Comment by intermezzio** [comment]
Could [this library](https://github.com/binance/binance-public-data/tree/master/python) (or some easier python sdk) be used to import data?
